CREATE TABLE db_versions (
  id SERIAL PRIMARY KEY,
  db_version INTEGER NOT NULL UNIQUE,
  created TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS users (
  user_id  SERIAL PRIMARY KEY,
  username VARCHAR(32) NOT NULL,
  password VARCHAR(100) NOT NULL
);
