name: Deploy to AWS Elastic Beanstalk
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
    - uses: actions/checkout@v3
    # - uses: dorny/paths-filter@v2
    #   id: changes
    #   with:
    #     filters: |
    #       client:
    #         - 'client/**'
    - name: Build React App
      # if: steps.changes.outputs.client == 'true'
      run: |
        cd client
        npm install
        npm run build
    - name: Build Server
      run: |
        npm install
        npm run build
    - name: Install Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install EB CLI using pip
      run: |
        python -m pip install --upgrade pip
        pip install awsebcli
    - name: Init EB CLI
      run: |
        eb init homepage --p "${{secrets.AWS_PLATFORM}}" --region "${{secrets.AWS_DEFAULT_REGION}}"
    - name: Deploy to Elastic Beanstalk
      run: |
        eb deploy