name: CI/CD
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1

      - uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build and run test
        env:
          RAILS_ENV: test

        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake db:create
          bundle exec rake db:migrate
          bundle exec rspec .
