name: CI/CD
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1

      - uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build and run test
        env:
          RAILS_ENV: test

        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake db:create
          bundle exec rake db:migrate
          bundle exec rspec .

      - name: Generate deployment package
        run: |
          zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: colinjsantee.com
          environment_name: colinjsanteecom-dev
          region: us-east-1
          version_label: ${{github.SHA}}
          deployment_package: deploy.zip
